apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: "kfserving-custom-model"
  labels:
    environment: dev
    app: boeing
spec:
  predictor:
    minReplicas: 3
    containers:
    - image: arunneo/kfserving-custom-model